name: Quality

on: [push]

jobs:
  build-verify-jdk11-postgres:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_DB: sqldsltests

    steps:
      - name: Setup PostgreSQL
        uses: gullerya/db-setup-action@v1.1.0
        with:
          image: 'postgres:alpine'
          port: ${{ env.POSTGRES_PORT }}
          username: ${{ env.POSTGRES_USER }}
          password: ${{ env.POSTGRES_PASS }}
          database: ${{ env.POSTGRES_DB }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Spotbugs
        run: mvn spotbugs:check

      - name: Test
        env:
          DB_TYPE: postgresql
          DB_HOST: localhost
          DB_PORT: ${{ env.POSTGRES_PORT }}
          DB_USER: ${{ env.POSTGRES_USER }}
          DB_PASS: ${{ env.POSTGRES_PASS }}
          DB_DB: ${{ env.POSTGRES_DB }}
        run: mvn --batch-mode --update-snapshots verify -DskipTests=false -Pcoverage

      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov